### PR TITLE
Fix dependencies to match upstream package

### PR DESCRIPTION
**Pull request by tpdownes**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This PR adds 2 extra maintainers from @google organization and updates the dependencies to match the upstream Python libraries. In particular, the full version string for upper-bounds are necessary because `3.0.0dev < 3` evaluates to `True`.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Thanks for adding yourself as a maintainer. I haven't had the reason to property maintain this feedstock for a while.

**Comment by tpdownes** [comment]
A recent commit you made unblocked a lot of upgrades to 2.x releases of software (good!) but I do think it would help to have more maintainers!

**Comment by hmaarrfk** [comment]
Honestly, I don't think that conda-forge releases development releases. 

I'm also not sure how conda evaluates version numbers. they are slightly different than pip but happy to get your hands to help!

**Comment by hmaarrfk** [comment]
> Thanks for adding yourself as a maintainer. I haven't had the reason to property maintain this feedstock for a while.

Sorry this was by no means sarcastic. I am happy to get your help!

**Pull request merged**
